### ISSUE TITLE
What is the `.ptsd` format?

### ISSUE THREAD

**Issue by jwarner112** [KernelEquinox/SAIcrypt#1]
Hello,

In a Linux-only household, I have need for a `.sai` file decryption utility. I've tried this one, but it's output is a `.ptsd` file which I'm unfamiliar with and can't find any information on. Can you offer some insight on this?

Thanks,
Jeff

**Comment by KernelEquinox** [comment]
Sure thing! The `.ptsd` extension just stands for "Paint Tool SAI Decrypted". The plaintext data is in a proprietary format that's used directly with Paint Tool SAI. I've got a collection of notes detailing which sections are for what on my home system; I'll get those later today and add that information to the repository.

**Comment by jwarner112** [comment]
Thanks! I'll give them a look as soon as they're in!
